# Generated by Django 4.0.2 on 2022-03-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('roles', models.JSONField()),
                ('name_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=128)),
                ('available_roles', models.JSONField()),
                ('name_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('bio', models.TextField()),
                ('username_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamUserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSquads.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSquads.user')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='sportSquads.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='members_with_roles',
            field=models.ManyToManyField(related_name='member_with_roles', through='sportSquads.TeamUserMembership', to='sportSquads.User'),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSquads.sport'),
        ),
        migrations.AddField(
            model_name='sport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportSquads.user'),
        ),
    ]
