# Generated by Django 4.0.2 on 2022-03-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportSquads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
