# Generated by Django 4.0.2 on 2022-03-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportSquads', '0003_alter_sport_image_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportSquads.userprofile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sportSquads.sport'),
        ),
    ]
