# Generated by Django 4.0 on 2022-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportSquads', '0004_alter_sport_author_alter_team_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members_with_roles',
            field=models.ManyToManyField(related_name='members_with_roles', through='sportSquads.TeamUserMembership', to='sportSquads.UserProfile'),
        ),
    ]
